theme: jekyll-theme-minimal
title: Liana Valdes
description: My projects website
logo: /images/waterfront.jpg
show_downloads: true
about: ./about.md
people: ./pages/people.md
research: /pages/research.md
sponsors: /pages/people.md

author:
  name: Liana Valdes
  bio: PhD candidate at FIU
  location: FIU, USA
